export const QUIZ_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  GRADING_PENDING: 'GRADING_PENDING',
  GRADED: 'GRADED',
  PUBLISHED: 'PUBLISHED',
});
